-- phpMyAdmin SQL Dump
-- version 4.7.9
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le :  ven. 21 sep. 2018 à 13:51
-- Version du serveur :  5.7.21
-- Version de PHP :  7.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `location_logement`
--

-- --------------------------------------------------------

--
-- Structure de la table `logement`
--

DROP TABLE IF EXISTS `logement`;
CREATE TABLE IF NOT EXISTS `logement` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci,
  `price` int(11) NOT NULL,
  `address` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nb_max_voyager` int(11) NOT NULL,
  `nb_room` int(11) NOT NULL,
  `coor_x` double NOT NULL,
  `coor_y` double NOT NULL,
  `img` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `logement`
--

INSERT INTO `logement` (`id`, `name`, `description`, `price`, `address`, `nb_max_voyager`, `nb_room`, `coor_x`, `coor_y`, `img`) VALUES
(1, 'Appartement', 'Notre appartement est doté de parquet et de poutres, il possède tout le charme des vieux appartements du Marais et du vieux Paris. Vous serez enchanté par sa chaleur et son confort.\r\nNotre appartement est situé à coté de République, dans le Nord du Marais, 3e arrondissement. Il n\'y a pas plus central et mieux desservi. Vous aurez le choix entre 5 stations de métro à 5 minutes à pied ou moins et 5 lignes de m-étro.\r\n\r\nL\'appartement mesure 55 m², 3 pièces, il est doté de 2 chambres avec une salle de bain, une cuisine et une vaste pièce à vivre de 25 m². Toutes ces pièces sont à votre disposition mise à part notre propre chambre.\r\n\r\nLa chambre qui vous accueillera (chambre bleue sur les photos) vous séduira par son coté cosy. Elle est équipée d\'un lit très confortable pour 2 personnes. Vous pourrez également profiter de la bibliothèque que la chambre abrite et consulter comme bon vous semble les livres, BD et magazines.\r\n\r\nVous pourrez vous détendre en prenant un bon bain dans la salle de bain ou bien en profitant de notre salon, doté d\'un vaste et moelleux canapé.', 34, 'Paris, France', 4, 3, 48.863715, 2.342697, '0011.jpg'),
(2, 'Magnifique maison en bambou au bord du fleuve', 'ituée dans la vallée sacrée de la rivière Ayung, cette maison en bambou est unique. Cette maison créée en 2010 fait partie d\'un ensemble communautaire planifié de luxueuses villas en bambou avec toits blonds distinctifs. Pénétrer dans la maison est une régal pour les yeux et une vitrine montrant comment le bambou noir et blanc peut être combiné sous toutes ses formes et motifs afin de créer une superbe collection de sols, de murs, de plafonds, d\'escaliers et de balustrades luxueux. Même le toit est un agencement innovant de bardeaux de bambou. \r\n\r\nLa maison Sunrise, perchée en bordure de la gorge de la rivière Ayung, comprend quatre étages, 3 chambres doubles, chacune avec salle de bains, une cuisine, un salon et une salle à manger avec des vues imprenables, un bassin de plongée, un espace de travail à l\'étage supérieur (4ème), et des panoramas fantastiques et encore vierges. Les invités pénètrent par le troisième étage, où se trouvent le salon, une cuisine et une salle des médias. En descendant les escaliers vers le deuxième étage, on trouve les chambres nord et sud, chacune avec des ventilateurs et des salles de bains attenantes. L\'étage inférieur comprend la suite parentale climatisée. La suite parentale comprend également une salle de séchage avec déshumidificateur. Toutes les chambres ont des stores en bambou pour préserver votre intimité. A partir de l\'étage inférieur, les invités peuvent sortir de la maison et descendre les escaliers qui mènent au bassin de plongée et au jardin privé, perchés littéralement au bord de la vallée de la rivière. Toutes les chambres sont meublées avec de superbes meubles en bambou qui complètent parfaitement le décor. Le paysage et la vue de la maison émerveillent les invités. Si vous venez à plus de 6 personnes, faites-nous le savoir : nous pouvons organiser des possibilités de couchage supplémentaires. \r\n\r\nLa maison inclut le WIFI, une télévision avec lecteur DVD (apporter des DVD si vous voulez les visionner) et la télévision par satellite. Un accès est également disponible vers l\'espace commun, qui comprend une piscine naturelle, un pavillon et un restaurant.', 200, 'Abiansemal, Bali, Indonésie', 8, 5, -8.556803, 115.22626, '15743.jpg'),
(3, 'Lussuoso, Vue incroyable\r\n', 'Appartement donnant sur le lac neuf et luxueux en résidence avec piscine ouverte en été du 15 juin au 15 septembre, court de tennis, bowling et parc (utilisation inclus dans le prix). Vue extraordinaire. Place de parking de la propriété. À 150 mètres du centre du village médiéval de Riva di Solto. Appartement de trois pièces + salle de bains + 2 terrasses. Internet wi-fi: 1,50 € par jour (wifi Internet: 1,50 € par jour.', 75, 'Riva, Lombardie, Italie', 6, 2, 44.97898259999999, 10.710922299999993, 'Salon-apt-6-2.jpg'),
(4, 'Sardaigne Navarrese, Vacance vue sur mer', 'Notre nouvel appartement est moderne et avec vue sur la mer. Proche de la plage (300 mt) et des services. Près du port touristique pour les excursions en bateau et les sentiers de trekking / escalade / VTT. Confortable avec parking et wi-fi. Nous vous attendons en Sardaigne! Essayez-nous!', 43, 'Santa Maria Navarrese', 3, 1, 39.9882901, 9.686215199999992, '15743.jpg'),
(5, 'Chambre élégante et privée', 'Le 20 mètres carrés (215 pieds carrés) dispose d\'un lit queen size avec des draps et serviettes, une couette en duvet, une télévision connectée, radio de base, bouilloire électrique et des articles de toilette de base. La chambre partage une luxueuse salle de bains en marbre avec bidet et douche.', 29, 'Berlin, Allemagne', 2, 1, 52.52000659999999, 13.404953999999975, 'Salon-apt-6-2.jpg'),
(6, 'Appartement douillet et calme au centre-ville', 'Très bel appartement, rénové en 2013, situé près du campus de l\'hôpital universitaire de la Charité et de l\'université BEUTH dans l\'ancien quartier ouvrier Wedding, correspondant à l\'actuel quartier Mitte (centre).\r\n55 mètres carrés, deux chambres, cuisine & salle de bain pour accueillir de 1 à 4 personnes.', 58, 'Berlin, Allemagne', 4, 2, 52.52000659999999, 13.404953999999975, '0011.jpg'),
(7, 'T1 Bis au coeur du vieux Bordeaux', 'Ce beau studio avec sa chambre en mezzanine, a été rénové et aménagé pour en faire un nid cosy et confortable. Il est situé dans un ancien hôtel particulier en pierre, au cœur de la vieille ville (rue des faussets), idéal pour découvrir Bordeaux.', 50, 'Bordeaux, France', 4, 1, 44.837789, -0.5791799999999512, '15743.jpg'),
(8, 'Appartement exquis avec des espaces ouverts et de la lumière', 'Être à Barcelone Dans le centre de Barcelone. Et rester dans un espace unique avec de hauts plafonds, propre style et beaucoup de lumière naturelle. Ce n\'est pas un rêve Cet appartement existe. Et c\'est à l\'Eixample.', 290, 'La Nova Esquerra de l\'Eixample, Barcelone, Catalunya, Espagne', 8, 3, 41.3837327, 2.147479999999973, 'Salon-apt-6-2.jpg'),
(9, 'Beau studio au centre', 'Beau studio avec capacité pour 2 personnes, dispose d\'un lit double, et un canapé-lit, cuisine avec appareils électroménagers, plaque vitrocéramique, machine à laver, réfrigérateur, micro-ondes, ustensiles de cuisine, ADSL est également disponible. Il est situé dans le centre de Madrid à côté du métro.\r\n\r\nIl est situé dans une zone très centrale et à proximité des zones commerçantes, des cinémas, des théâtres et de la vie nocturne de Madrid, en plus de tous les endroits les plus touristiques de Madrid. \r\nLa communication est variée, métro, bus, à côté de l\'appartement. \r\nL\'appartement est idéal pour des vacances à Madrid, dans le centre-ville, car il est très bien situé dans une zone très centrale et n\'est pas bruyant.', 48, 'Madrid, Espagne', 2, 1, 40.4167754, -3.7037901999999576, '0011.jpg'),
(10, 'Zen Mouraria - Votre appartement à Lisbonne', 'Juste dans le centre historique de Lisbonne, à côté du château où la ville est née et à proximité des principales attractions touristiques. Ce quartier a été multiculturel pour les mille dernières années. La ville et sa musique, Fado, sont nés ici.\r\nDescendez la rue et vous êtes au centre-ville, montez la rue et vous êtes dans les beaux belvédères de Lisbonne, où toutes les images de carte postale ont été prises.\r\nLe métro, les bus et même les célèbres tramways jaunes sont à seulement 3 minutes.', 10, 'Lisbonne, Portugal', 2, 1, 38.7222524, -9.139336599999979, '15743.jpg'),
(11, 'Appartement rustique et romantique dans le centre historique', 'Imprégnez-vous de l\'ambiance vintage d\'une maison rénovée dans l\'un des quartiers les plus charmants de Porto, au cœur du site classé au patrimoine mondial de l\'UNESCO. Installés dans un bâtiment du XIXe siècle, les murs en pierre, les jolis sols à motifs et les murs blancs créent une esthétique décontractée.', 58, 'Porto, Portugal', 4, 1, 41.1579438, -8.629105299999992, 'Salon-apt-6-2.jpg'),
(12, 'Sarabande Genval jacuzzi Lac', 'Sur le magnifique lac de Genval, la Sarabande est un lieu idéal pour passer une nuit, un week-end ou même une semaine entière. Vous avez à votre disposition un jacuzzi privé, TV, Netflix, WiFi, grand canapé-lit, cuisine entièrement équipée, douche avec vue panoramique, terrasse plein sud,\r\nNombreuses activités sur le lac. Nous proposons également des vélos à louer.', 110, 'Overijse, Belgique', 2, 1, 50.77381, 4.534750000000031, '0011.jpg'),
(13, 'Saint Boniface Rooftop', 'Agréable petit flat sous les toits de Bruxelles.\r\nIdéal pour deux personnes ou une personne seule.', 60, 'Bruxelles, Belgique', 2, 1, 50.8503396, 4.351710300000036, '15743.jpg'),
(14, 'Maison romantique en Carinthie', 'Une boîte troad originale, convertie en une cabane confortable. Idéal pour 2 personnes qui aiment profiter de la vie à la campagne et du magnifique paysage de Carinthie. \r\nA proximité se trouve une merveilleuse des eaux pour la pêche à la mouche. Les cartes peuvent être achetées chez nous.', 80, 'Trieblach, Autriche', 2, 1, 46.55011, 14.433970000000045, 'Salon-apt-6-2.jpg'),
(15, 'Appartement de 80m2', 'L\'appartement entièrement équipé est situé au centre du 3ème étage (NO ELEVATOR) dans un bel immeuble ancien du centre de Graz. L\'appartement a été récemment rénové, nouvellement meublé et offre un confort pour jusqu\'à 4 personnes.', 80, 'Graz, Autriche', 4, 2, 47.070714, 15.439503999999943, '0011.jpg'),
(16, 'SPA près de Sofia-Plovdiv. Piscine extérieure chauffée 24/7!', 'Bienvenue dans notre appartement all seasons SPA!\r\n\r\nSitué dans un village de montagne en 1 heure de route de Sofia et à seulement 30 minutes en voiture de la célèbre station de ski Borovets: \r\n- piscines thermales avec eau chaude (piscine extérieure 24/7 et une intérieure) bon pour chaque saison \r\n- eau thermale dans le tube de l\'appartement \r\n- Internet Wi-Fi rapide \r\n- cuisine entièrement équipée \r\n-- restaurant \r\n- massages, sauna et bains hydromassants dans l\'hôtel adjacent \r\n- location de vélo \r\n- billard et table de tennis \r\n- promenades en montagne', 254, 'Pchelin, Bulgarie', 6, 2, 42.8847412, 26.773344899999984, '15743.jpg'),
(17, 'Appartement de luxe confortable, meilleur quartier', 'Charmant appartement dans un quartier calme, à seulement 15 minutes à pied du centre idéal (Université et Cathédrale Saint-Alexandre-Nevski), avec toutes les commodités dont vous aurez besoin pour vous sentir comme chez vous et profiter de votre séjour à Sofia.', 589, 'Sofia, Bulgarie', 10, 6, 42.6977082, 23.321867500000053, 'Salon-apt-6-2.jpg'),
(18, 'Vue sur la mer de luxe Villa sur la côte de Paphos', 'Superbe villa sur la plage avec un grand balcon double, vue panoramique sur la mer et une piscine; situé dans un endroit paisible. 50m de la mer et à proximité du port de Paphos et Coral Bay. Une villa de construction chypriote traditionnelle avec 4 chambres (8 couchages: 3 chambres doubles + 1 chambre double) * Lit supplémentaire disponible sur demande.\r\n\r\nVue aérienne ici - s\'il vous plaît regarder! : Apollo Beach Paphos Chypre sur YouTube', 360, 'Paphos, Chypre', 8, 4, 34.7720133, 32.429736899999966, '0011.jpg'),
(19, 'Mignon Apt. Près des criques de plage + wifi', 'L\'appartement bénéficie d\'un emplacement privilégié pour être à 5-10 minutes à pied de la plage la plus proche, la plage des pompiers.', 45, 'Paralimni, Chypre', 4, 2, 35.0352421, 33.98614900000007, 'Salon-apt-6-2.jpg'),
(20, 'La meilleure position à Hvar!', 'Appartement situé en dessous de la forteresse de Spanjola avec la position centrale et vue sur le magnifique port de Hvar et les îles Pakleni!', 72, 'Hvar, Croatie', 2, 1, 43.1541875, 16.65270989999999, '15743.jpg'),
(21, 'Studio Lara - Emplacement parfait', 'Le studio est situé dans un quartier résidentiel calme de Split, à seulement 5 minutes à pied du centre-ville et de la plage locale. Il y a un balcon dans le jardin avec une belle vue sur la mer et les îles. La surface de l\'appartement est de 24 m2. L\'appartement dispose d\'un lit king size. Internet haut débit Wi-Fi, Air conditionné, draps, serviettes et nettoyage tout inclus dans le prix. Il y a aussi un parking gratuit dans la rue, juste en face de la maison. \r\nLa ville de Split est l\'une des plus anciennes villes de la côte adriatique. Il est âgé de plus de 1700 ans à partir de la construction du palais de Dioclétien en l\'an 305, la recherche archéologique concernant la fondation de la ville comme la colonie grecque d\'Aspálathos au 6ème siècle avant JC, établit la tradition urbaine de la région des siècles plus vieux. Les lieux à visiter sont le palais de Dioclétien, le vieux centre, la riva, l\'église St. Duje ... etc \r\nLa qualité des eaux de la mer Adriatique, ainsi que l\'immense nombre de criques, d\'îles et de canaux, font de la Dalmatie un lieu attractif pour les courses nautiques, le tourisme nautique et le tourisme en général. La Dalmatie comprend également plusieurs parcs nationaux qui sont des attractions touristiques.', 1500, 'Split, Croatie', 16, 8, 43.5081323, 16.440193499999964, 'Salon-apt-6-2.jpg'),
(22, 'Appartement-terrasse, 4-5 chambres + 5 balcons', 'L\'appartement est spacieux et est très ensoleillé. Il a 5 petits balcons et une terrasse. Il y a 3 chambres, une petite, une moyenne et une grande. De plus, il y a deux chambres mansardées sous le toit à mi-hauteur, meublées avec des lits.\r\n\r\nNotez deux choses avant de réserver\r\n1) Notre appartement est au 5ème étage sans ascenseur \r\n2) Une station de métro est en cours de construction à l\'extérieur en ce moment. Cela fait du bruit, surtout lorsque les fenêtres et les portes sont ouvertes.', 200, 'Copenhague, danemark', 10, 5, 55.6760968, 12.568337199999974, '0011.jpg'),
(23, 'Merveilleux apt. Juste dans la ville!', 'Facile d\'enregistrement car j\'ai un restaurant à proximité, ouvert 11 heures et fermé 10 heures.', 110, 'Blankavej, Danemark', 4, 2, 55.66752952132192, 12.511088130786106, '15743.jpg'),
(24, 'Calme, chaleureux et à 5 minutes à pied de la vieille ville.', 'Appartement élégant et confortable, à seulement 5 minutes à pied de la vieille ville de Tallinn, situé dans un quartier résidentiel calme mais avec toutes les commodités juste au coin de la rue. \r\nNotre appartement est une alternative parfaite pour une chambre d\'hôtel dans le centre-ville.', 45, 'Tallinn, Estonie', 2, 1, 59.43696079999999, 24.753574699999945, '0011.jpg'),
(25, 'Belle maison avec sauna en bois', 'Une jolie maison de sauna en bois qui se trouve au bord d\'un magnifique lac avec sa jetée privée entourée de forêts luxuriantes, de champs et de nombreuses espèces sauvages.', 89, 'Maaritsa, Estonie', 6, 3, 58.1498174, 26.707652199999984, '15743.jpg'),
(26, 'Maison traditionnelle en Laponie', 'Maison de campagne privée unique dans la nature et les bois tranquilles en Laponie! \r\nAppartement privé avec belle atmosphère et avec équipement moderne - cuisinière électrique et four, réfrigérateur, TV, wi-fi et cheminée. Situation tranquille dans la nature, facile à atteindre.', 79, 'Laponie, Finlande', 4, 2, 67.9222304, 26.50464379999994, '0011.jpg'),
(27, 'Arty intérieur en 1900 maison en bois', 'Design intérieur dans la zone la plus sympathique à Helsinki! Complètement rénové, bien équipé, studio confortable dans idyllique, plus de 100 ans maison en bois. Rue calme, connexion rapide au centre et à l\'aéroport. \r\nWifi gratuit.', 40, 'Helsinki, Finlande', 2, 1, 60.16985569999999, 24.93837910000002, 'Salon-apt-6-2.jpg');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
